[package]
name = "smolprog"
version = "0.1.0"
edition = "2021"

[features]
date = []
battery = []
cpu = []
memory = []
network = []
sessions = []
volume = []

default = ["date"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
